---
title: A developer's wonder garden
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
    comments: true
  uploads:
    title: Uploads
    output: true
email: xzhang@zhresearches.com
description: 'A home to share my passion.

'
baseurl: 
url: https://www.zhresearches.com
enforce_ssl: www.zhresearches.com
twitter_username: zhangxd6
github_username: zhangxd6
linkedin_username: xiangdong-zhang-1b89923
excerpt_separator: "<!--more-->"
markdown: kramdown
