# Site settings

title: A developer's wonder garden # Title of your site
email: xzhang@zhresearches.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
 A home to share my passion.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhresearches.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     zhangxd6  # Replace this with your Twitter username
github_username:      zhangxd6  # Replace this with your GitHub username
linkedin_username:    xiangdong-zhang-1b89923  # Replace this with your LinkedIn username
excerpt_separator:   <!--more-->
# Build settings
markdown: kramdown
